name: Quality Assurance

'on':
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.head_ref || github.actor }}
    cancel-in-progress: true

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v3.5.3
            -
                uses: ScribeMD/docker-cache@0.3.3
                with:
                    key: ${{ runner.os }}-docker-${{ hashFiles('Makefile') }}
            -
                run: make test
